### ISSUE TITLE
Publish artifact to Maven Central

### ISSUE THREAD

**Issue by electrum** [codecentric/NSMenuFX#1]
Cool project! Any plans to publish the artifact to Maven Central?

**Comment by 0x4a616e** [comment]
Thx! I'd like to add some minor things allowing for simpler usage in cross-platform projects first. But after that, i'll try to publish it on maven central.

**Comment by 0x4a616e** [comment]
Sorry... it took me a while but it's now published to Maven Central!

```
<dependency>
    <groupId>de.codecentric.centerdevice</groupId>
    <artifactId>centerdevice-nsmenufx</artifactId>
    <version>1.0.0</version>
 </dependency>
```
