### ISSUE TITLE
Provide a Maven release with localization

### ISSUE THREAD

**Issue by pejaham** [codecentric/NSMenuFX#11]
Thanks for sharing the menu adapter - a great help for my ScalaFXML applications.

Could you provide a new Maven release which includes the latest localization feature? Currently I am using a GIT clone of the project and create a private build to take advantage of the German localization.

Thanks and regards,
Peter

**Comment by 0x4a616e** [comment]
Hi Peter, glad to hear that! I'll upload a new release within next week!

**Comment by 0x4a616e** [comment]
New version has been uploaded:
    <dependency>
        <groupId>de.codecentric.centerdevice</groupId>
        <artifactId>centerdevice-nsmenufx</artifactId>
        <version>2.1.0</version>
    </dependency>
