### ISSUE TITLE
Checkmark icon for frontmost window

### ISSUE THREAD

**Issue by msgilligan** [codecentric/NSMenuFX#12]
The Windows menu lists displayed windows and allows bringing a window to the front by selecting it. (Cool!)

However, it should place a checkmark in front of the name of the currently selected window.

**Comment by 0x4a616e** [comment]
I'm currently adding some own native methods to access the native menu bar. This allows to use cocoas own window menu handling that'll automatically add the checkmark to the currently selected window menu item. This also makes the java code a bit easier.

**Comment by 0x4a616e** [comment]
Should be fixed with the latest commits. I'll upload a new jar to maven central soon.

**Comment by msgilligan** [comment]
Any word on the new jar?

**Comment by 0x4a616e** [comment]
New jar has just been uploaded!
