### ISSUE TITLE
Create CHANGELOG or release notes

### ISSUE THREAD

**Issue by msgilligan** [codecentric/NSMenuFX#15]
It would be nice to have a CHANGELOG or release notes showing each release and major changes made in that release. For example: [bitcoinj-addons CHANGELOG](https://github.com/msgilligan/bitcoinj-addons/blob/master/CHANGELOG.adoc)

(If you're OK with the above example format, I can make a pull request -- are you open to using AsciiDoctor markdown for the CHANGELOG and/or README? I prefer it for all documentation, but am happy to use standard Github markdown if you prefer)

**Comment by 0x4a616e** [comment]
Having a changelog is definitely a good idea. However I'm not (yet) using AsciiDoctor but use the default Idea markdown editor. So it would probably be better to use standard Github markdown, so that everything will be displayed correctly in browser.

**Comment by 0x4a616e** [comment]
Added a simple changelog mardown file
