### ISSUE TITLE
Any way to change the icon that displays in "About"?

### ISSUE THREAD

**Issue by FetchLeo** [codecentric/NSMenuFX#17]
Hi,

I noticed that NSMenuFX always loads a generic icon from the system. Will it ever be possible to change this?

Also, will the copyright text ever be customizable?
These would both be nice things to see.

Thanks.

**Comment by 0x4a616e** [comment]
You can always use the `AboutStageBuilder` to create a custom "About" menu like this

```
AboutStageBuilder stageBuilder = AboutStageBuilder.start(labelMaker.getLabel(LabelName.ABOUT, appName))
				.withAppName(appName).withCloseOnFocusLoss().withCopyright("Copyright \u00A9 " + Calendar
						.getInstance().get(Calendar.YEAR));
```

There, you also have other options to customise the dialog. But you're right, the API could be improved there. I'll see If i can come up with a better solution.

**Comment by 0x4a616e** [comment]
What about that: https://github.com/codecentric/NSMenuFX/blob/master/src/test/java/de/codecentric/centerdevice/sample/AboutMenu.java

**Comment by FetchLeo** [comment]
Looks good! Thanks!
