### ISSUE TITLE
LabelMaker.getResourceName() returns wrong file name.

### ISSUE THREAD

**Issue by glick** [codecentric/NSMenuFX#18]
In the class LabelMaker.java the method getResourceName() return wrong name.
You should use locale.toLanguageTag() or concat at least 2 strings manually <lang>_<country>, e.g. menu_labels_fr_FR.properties.
For example, in Canada and in France using French, but different dialects.

**Comment by 0x4a616e** [comment]
We'll now try to load `menu_labels_fr_FR.properties`, if that fails fall back to `menu_labels_fr.properties` and if that also fails, fall back to EN.
