### ISSUE TITLE
NSMenuFX always crash in mac os sierra 10.12.4

### ISSUE THREAD

**Issue by spartajet** [codecentric/NSMenuFX#23]
Hi, I have integrate your NSMenuFX into my javafx application. But, it will always lead my mac os crash, when it crash, I couldn't use my keyboard, mouse and control panel, so I can not get the error log. 
But, some days ago, I use the method `menuBar.setUseSystemMenuBar(true);` this method will lead my os crashing. 
So, Sir, I find that you use the same method in class `MenuBarUtils`, line 20.
I think it may be the bug of the mac os sierra or the jdk.

My jdk : 1.8.0_131
My os : mac os sierra 10.12.4
My IDE: Intellij IDEA 2017.1

**Comment by 0x4a616e** [comment]
Hi! That certainly should not happen. Do you maybe have some minimalistic code sample that causes the crash. And: Is this also happening when you run one the examples here?https://github.com/codecentric/NSMenuFX/tree/master/src/test/java/de/codecentric/centerdevice/sample

**Comment by 0x4a616e** [comment]
Closing this issue due to timeout 😉
